name: Fetch Quickstarts

on:
  workflow_dispatch:
  schedule:
    - cron: '0 1,5,9,13,17,21 * * *' # Every 4 hours staggered by 1 hour

env:
  BOT_NAME: nr-opensource-bot
  BOT_EMAIL: opensource+bot@newrelic.com
  NODE_OPTIONS: '--max-old-space-size=4096'

jobs:
  fetch-quickstarts:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
        with:
          ref: main

      - name: Setup node.js
        uses: actions/setup-node@v1
        with:
          node-version: 16

      - name: Cache dependencies
        id: yarn-cache
        uses: actions/cache@v2
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-node-modules-${{ hashFiles('**/yarn.lock') }}

      - name: Install dependencies
        if: steps.yarn-cache.outputs.cache-hit != 'true'
        run: yarn install --frozen-lockfile

      - name: Fetch quickstarts
        run: yarn run fetch-quickstarts
        env:
          NR_API_URL: 'https://api.newrelic.com/graphql'
          NR_API_TOKEN: ${{ secrets.NR_API_TOKEN }}

      - name: Temporarily disable branch protection
        id: disable-branch-protection
        uses: actions/github-script@v5
        with:
          github-token: ${{ secrets.DEVEX_OPENSOURCE_BOT_TOKEN }}
          previews: luke-cage-preview
          script: |
            const result = await github.rest.repos.updateBranchProtection({
              owner: context.repo.owner,
              repo: context.repo.repo,
              branch: 'main',
              required_status_checks: null,
              restrictions: null,
              enforce_admins: null,
              required_pull_request_reviews: null
            })
            console.log("Result:", result)

      - name: Commit changes
        id: commit-changes
        run: |
          git config --local user.email "${{ env.BOT_EMAIL }}"
          git config --local user.name "${{ env.BOT_NAME }}"
          git add ./src/data/quickstarts.json
          git diff-index --quiet HEAD ./src/data/quickstarts.json || git commit -m 'chore(quickstarts): updated quickstarts'
          echo "::set-output name=commit::true"

      - name: Push Commit
        if: steps.commit-changes.outputs.commit == 'true'
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.DEVEX_OPENSOURCE_BOT_TOKEN }}
          branch: main

      - name: Re-enable branch protection
        id: enable-branch-protection
        if: always()
        uses: actions/github-script@v5
        with:
          github-token: ${{ secrets.DEVEX_OPENSOURCE_BOT_TOKEN }}
          previews: luke-cage-preview
          script: |
            const result = await github.rest.repos.updateBranchProtection({
              owner: context.repo.owner,
              repo: context.repo.repo,
              branch: 'main',
              required_status_checks: {
                strict: false,
                contexts: [
                  'Gatsby Build Service - instant-observability-website'
                ]
              },
              restrictions: null,
              enforce_admins: true,
              required_pull_request_reviews: {
                dismiss_stale_reviews: true,
                required_approving_review_count: 1
              }
            })
            console.log("Result:", result)
